### ISSUE TITLE
Partial derivatives only program?

### ISSUE THREAD

**Issue by MetodiV** [Hamza-STI/CASYMBA#3]
Bonjour 

J’ai essayé d’installer l’application, mais même avec tous les autres programmes disparus, il semble que ma mémoire soit insuffisante. Je me demandais si vous pouviez publier un programme avec seulement l’option de calculatrice de dérivés partiels. Merci d’avance

**Comment by adriweb** [comment]
Il ne devrait pas y avoir ce probleme, donc il y  a un soucis avec la configuration de ta calculatrice.

- Commence par mettre en memoire d'archive (ou sauver sur l'ordi) tes programmes actuellement en RAM
- Appuie et maintiens enfonce le bouton reset au dos, pendant 3-4s, ca devrait reset la RAM et resoudre donc les problemes de RAM.
- mets a jour en OS 5.4 si tu as une version avant celle la.
- reinstalle les programmes voulus

**Comment by MetodiV** [comment]
J’ai essayé, ce sont maintenant les programmes que j’ai. Ma version est 5.8. Cela ne fonctionne toujours pas. J’ai eu le même problème avec l’autre programme PineCAS. « La mémoire est insuffisante pour effectuer le calcul. Vérifiez les récursions ou les boucles infinies. Ex Y1=Y1"

![image](https://user-images.githubusercontent.com/131024535/232571185-88c11cad-3118-4b89-aefe-3dc46101973a.png)

**Comment by MetodiV** [comment]
J’avais également supprimé les autres programmes, mais je ne pense pas qu’ils soient assez gros de toute façon pour causer le problème.

**Comment by adriweb** [comment]
Toutes les variables de type "program" (et "protected program", d'autant plus) n'ont pas besoin d'etre en RAM, au contraire, il faut qu'elles soient en archive.
Bref, suivre la liste d'instructions que j'ai donne!

**Comment by adriweb** [comment]
Normal que ce soit verrouillé, pour des programmes ASM. D'autres programmes de lancent bien ou pas ?

**Comment by MetodiV** [comment]
https://user-images.githubusercontent.com/131024535/232577599-c8c2b444-f024-4a6f-a884-53c3167513b3.mov

**Comment by adriweb** [comment]
Peut être que le "Ans" nécessaire n'est pas correctement géré avec l'utilisation de Césium... il faudrait essayer avec AsmHook (une fois lancé/installé, il suffit de lancer les programmes directement depuis le menu prgm)

**Comment by adriweb** [comment]
Non non tres bien, maintenant d'autres personnes sauront aussi.
