### ISSUE TITLE
Comportement étrange lors de la simplification de polynômes de "grande" taille

### ISSUE THREAD

**Issue by Mr-FuzzyPenguin** [Hamza-STI/CASYMBA#5]
J'ai remarqué que lorsque l'on donne à CASYMBA un grand polynôme comme :
((20-A)/270) + ((0-A)/10000) + ((B-(A+10))/620) + (((B+16)-(A+10))/430)

Le résultat attendu est le suivant :
-(2786491/359910000)A + (21/5332)B + (25877/359910)

Cela donne quelque chose d'autre qui n'est pas entièrement simplifié. Une idée ? Peut-être n'ai-je pas utilisé la bonne façon de simplifier ? La façon dont j'ai essayé de faire comprendre à CASYMBA qu'il devait la simplifier était de taper l'équation avec des guillemets (pour qu'elle soit stockée dans Ans). J'ai ensuite exécuté prgmCASYMBA.

Traduit avec DeepL.com (version gratuite)

**Comment by Hamza-STI** [comment]
Bonjour,

Merci, c'est bien un bug niveau programmation. 
J'ai corrigé sauf que le resultat est sous-forme de fraction.
